apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Bienvenue VDL !</title>
      </head>
      <body>
        <h1>Bienvenue VDL !</h1>
        <p>En direct du pod nginx</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    app.openshift.io/route-url: 'https://nginx.k3d.localhost'
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /usr/share/nginx/html
        env:
          - name: MYVARIABLE
            value: "Hello"
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-configmap
